// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Navber from "@/components/Navber";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}
//         <Navber />
//       </body>
//     </html>
//   );
// }



// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import NextTopLoader from "nextjs-toploader";

// import "./globals.css";
// import Navber from "@/components/Navber";
// import ClientLayout from "./ClientLayout";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Aftab Ahmed Portfolio",
//   description: "Full Stack Developer Portfolio",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//  <html lang="en" suppressHydrationWarning
//       className={`${geistSans.variable} ${geistMono.variable}`}
//     >
//       <body className="min-h-screen overflow-x-hidden bg-slate-50 dark:bg-slate-950 ">

//         <NextTopLoader
//           color="#2563eb"
//           height={3}
//           showSpinner={false}
//         />

//         <ClientLayout>
//           <Navber />
//           {children}
//         </ClientLayout>

//       </body>
//     </html>
//   );
// }




import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import NextTopLoader from "nextjs-toploader";

import "./globals.css";
import Navber from "@/components/Navber";
import ClientLayout from "./ClientLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Aftab Ahmed Portfolio",
  description: "Full Stack Developer Portfolio",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable}`}
    >
      <body
        suppressHydrationWarning
        className="min-h-screen overflow-x-hidden bg-slate-50 dark:bg-slate-950"
      >
        <NextTopLoader
          color="#2563eb"
          height={3}
          showSpinner={false}
        />

        <ClientLayout>
          <Navber />
          {children}
        </ClientLayout>

      </body>
    </html>
  );
}